// Shared blog posts data
export interface BlogPost {
    slug: string;
    title: string;
    excerpt: string;
    date: string;
    category: string;
    link: string;
    thumbnail: string;
    content?: string;
}

export const blogPosts: BlogPost[] = [
    {
        slug: "academic-cv-business-value",
        title: "A Strong Academic CV Fails When It Hides Its Business Value",
        excerpt: "A guide to translating academic achievements into business language using the A.C.T.O.R. framework for PhDs transitioning to industry.",
        date: "2025-12-08",
        category: "Career Development",
        link: "https://www.linkedin.com/feed/update/urn:li:activity:7403755092274769925/",
        thumbnail: "/images/blog-thumbnails/academic-cv.jpg",
        content: "This is a LinkedIn post about translating academic CVs. The full content is available on LinkedIn.",
    },
    {
        slug: "finnish-learning",
        title: "Is it possible to learn Finnish fluently in less than a year?",
        excerpt: "Exploring the journey of learning Finnish and what it really takes to achieve fluency in less than a year.",
        date: "2024-12-01",
        category: "Language Learning",
        link: "https://www.linkedin.com/feed/update/urn:li:activity:7363829978519547905/",
        thumbnail: "/images/blog-thumbnails/finnish-learning.jpg",
        content: "This is a LinkedIn post about learning Finnish. The full content is available on LinkedIn.",
    },
    {
        slug: "unicorn-startup",
        title: "What does it really take to build a unicorn?",
        excerpt: "Insights into what it truly takes to build a unicorn startup and the journey behind successful companies.",
        date: "2024-11-15",
        category: "Entrepreneurship",
        link: "https://www.linkedin.com/feed/update/urn:li:activity:7381726751145521152/",
        thumbnail: "/images/blog-thumbnails/unicorn-startup.jpg",
        content: "This is a LinkedIn post about building unicorn startups. The full content is available on LinkedIn.",
    },
    {
        slug: "building-opportunities",
        title: "From no job, no money, no network to building opportunities one step at a time.",
        excerpt: "A personal story about building opportunities from scratch and the journey of transformation.",
        date: "2024-11-10",
        category: "Career Development",
        link: "https://www.linkedin.com/feed/update/urn:li:activity:7384516520510406656/",
        thumbnail: "/images/blog-thumbnails/building-opportunities.jpg",
        content: "This is a LinkedIn post about building opportunities. The full content is available on LinkedIn.",
    },
    {
        slug: "linkedin-platform",
        title: "LinkedIn is my favorite professional platform, but it's not perfect.",
        excerpt: "Reflections on using LinkedIn as a professional platform, its strengths and areas for improvement.",
        date: "2024-10-25",
        category: "Professional Development",
        link: "https://www.linkedin.com/feed/update/urn:li:activity:7373649192499630080/",
        thumbnail: "/images/blog-thumbnails/linkedin-platform.jpg",
        content: "This is a LinkedIn post about LinkedIn as a platform. The full content is available on LinkedIn.",
    },
    {
        slug: "finnish-integration",
        title: "From Marie Curie Postdoc Fellow to Night-Shift Worker: My Real Finnish Integration Story",
        excerpt: "A candid account of the real journey from academic research to building a new life in Finland.",
        date: "2024-10-20",
        category: "Integration & Career",
        link: "https://www.linkedin.com/feed/update/urn:li:activity:7391769210210729984/",
        thumbnail: "/images/blog-thumbnails/finnish-integration.jpg",
        content: "This is a LinkedIn post about Finnish integration. The full content is available on LinkedIn.",
    },
    {
        slug: "communities-finland",
        title: "Are you an international professional in Finland looking to connect with like-minded communities?",
        excerpt: "A guide to finding and connecting with communities for international professionals in Finland.",
        date: "2024-09-15",
        category: "Community Building",
        link: "https://lnkd.in/dhV4uEzj",
        thumbnail: "/images/blog-thumbnails/communities-finland.jpg",
        content: "This is a LinkedIn post about communities in Finland. The full content is available on LinkedIn.",
    },
    {
        slug: "volunteering-finland",
        title: "Looking for volunteering opportunities in Finland to boost your skills and network?",
        excerpt: "Exploring volunteering opportunities in Finland that can help you develop skills and expand your network.",
        date: "2024-09-10",
        category: "Career Development",
        link: "https://lnkd.in/dsx76gEQ",
        thumbnail: "/images/blog-thumbnails/volunteering-finland.jpg",
        content: "This is a LinkedIn post about volunteering. The full content is available on LinkedIn.",
    },
    {
        slug: "recruitment-events",
        title: "Are you looking to advance your career in Finland? Don't miss these top recruitment events designed for international talent!",
        excerpt: "A curated list of top recruitment events in Finland specifically designed for international professionals.",
        date: "2024-09-05",
        category: "Career Development",
        link: "https://lnkd.in/dD_p6h5T",
        thumbnail: "/images/blog-thumbnails/recruitment-events.jpg",
        content: "This is a LinkedIn post about recruitment events. The full content is available on LinkedIn.",
    },
    {
        slug: "mentoring-programs",
        title: "Looking to advance your career or give back by mentoring others? Check out these top mentoring programs in Finland!",
        excerpt: "Discover top mentoring programs in Finland for both career advancement and giving back to the community.",
        date: "2024-08-28",
        category: "Mentoring",
        link: "https://lnkd.in/dj4rUwpY",
        thumbnail: "/images/blog-thumbnails/mentoring-programs.jpg",
        content: "This is a LinkedIn post about mentoring programs. The full content is available on LinkedIn.",
    },
    {
        slug: "research-tools",
        title: "Essential Tools, Resources, and Academies for Researchers",
        excerpt: "A comprehensive guide to essential tools, resources, and academies that every researcher should know about.",
        date: "2024-08-20",
        category: "Research",
        link: "https://lnkd.in/ds2x6yqE",
        thumbnail: "/images/blog-thumbnails/research-tools.jpg",
        content: "This is a LinkedIn post about research tools. The full content is available on LinkedIn.",
    },
    {
        slug: "startup-programs",
        title: "Aspiring entrepreneur or startup founder in Finland? Explore these active pre-incubator, incubator, and accelerator programs to take your idea to the next level!",
        excerpt: "A detailed overview of active startup programs in Finland including pre-incubators, incubators, and accelerators.",
        date: "2024-08-15",
        category: "Entrepreneurship",
        link: "https://lnkd.in/dTSCnKvQ",
        thumbnail: "/images/blog-thumbnails/startup-programs.jpg",
        content: "This is a LinkedIn post about startup programs. The full content is available on LinkedIn.",
    },
    {
        slug: "linkedin-ssi",
        title: "Proud to share my LinkedIn Social Selling Index (SSI) score!",
        excerpt: "Sharing insights about LinkedIn Social Selling Index and what it means for professional networking.",
        date: "2024-08-10",
        category: "Professional Development",
        link: "https://lnkd.in/d_Qq54T3",
        thumbnail: "/images/blog-thumbnails/linkedin-ssi.jpg",
        content: "This is a LinkedIn post about LinkedIn SSI. The full content is available on LinkedIn.",
    },
    {
        slug: "hive-helsinki",
        title: "Spotlight on Hive Helsinki in its fifth anniversary",
        excerpt: "Celebrating Hive Helsinki's fifth anniversary and highlighting its impact on the tech education landscape.",
        date: "2024-08-05",
        category: "Education",
        link: "https://lnkd.in/duR_W-Kn",
        thumbnail: "/images/blog-thumbnails/hive-helsinki.jpg",
        content: "This is a LinkedIn post about Hive Helsinki. The full content is available on LinkedIn.",
    },
    {
        slug: "suomen-mestari",
        title: "Unforgettable Opportunity: Meeting the Co-Author of 'Suomen Mestari 1'",
        excerpt: "A memorable experience meeting the co-author of the famous Finnish language textbook 'Suomen Mestari 1'.",
        date: "2024-07-28",
        category: "Language Learning",
        link: "https://lnkd.in/dP_X3tXM",
        thumbnail: "/images/blog-thumbnails/suomen-mestari.jpg",
        content: "This is a LinkedIn post about Suomen Mestari. The full content is available on LinkedIn.",
    },
    {
        slug: "job-portals",
        title: "Discover Top Job Portals and Websites to Kickstart Your Career in Finland",
        excerpt: "A comprehensive guide to the best job portals and websites for finding opportunities in Finland.",
        date: "2024-07-20",
        category: "Career Development",
        link: "https://lnkd.in/dE74Q2Rc",
        thumbnail: "/images/blog-thumbnails/job-portals.jpg",
        content: "This is a LinkedIn post about job portals. The full content is available on LinkedIn.",
    },
    {
        slug: "hidden-job-market",
        title: "Unlocking the Hidden Job Market in Finland for All Professionals",
        excerpt: "Strategies and insights for accessing the hidden job market in Finland and finding opportunities beyond public listings.",
        date: "2024-07-15",
        category: "Career Development",
        link: "https://lnkd.in/de7C9fzm",
        thumbnail: "/images/blog-thumbnails/hidden-job-market.jpg",
        content: "This is a LinkedIn post about the hidden job market. The full content is available on LinkedIn.",
    },
];
