export const publications = [
    {
        title: "Experimental and computational approach on the corrosion inhibition properties of two newly pyrazole derivatives on carbon steel in acid medium",
        authors: "N Setti, A Barrahi, M Maatallah, Y Kaddouri, TB Hadda, H Outada, ...",
        journal: "Scientific Reports",
        volume: "15 (1), 3631",
        year: "2025",
        citations: 12,
        firstAuthor: false,
        field: "Corrosion",
    },
    {
        title: "Structural effect of bipyrazole derivatives on corrosion inhibition of carbon steel in 1 M HCl: weight loss, electrochemical measurements, XPS/SEM surface analysis, DFT and MC …",
        authors: "N Setti, A Barrahi, M Maatallah, Y Kaddouri, R Touzani, B Dikici, ...",
        journal: "Physical Chemistry Chemical Physics",
        volume: "27 (10), 5371-5394",
        year: "2025",
        citations: 11,
        firstAuthor: false,
        field: "Physical Chemistry",
    },
    {
        title: "New N-alkylated heterocyclic compounds as prospective NDM1 inhibitors: Investigation of in vitro and in silico properties",
        authors: "Y Kaddouri, B Bouchal, F Abrigach, M El Kodadi, M Bellaoui, ...",
        journal: "Pharmaceuticals",
        volume: "15 (7), 803",
        year: "2022",
        citations: 6,
        firstAuthor: true,
        field: "Medicinal Chemistry",
    },
    {
        title: "An Insight into All Tested Small Molecules against Fusarium oxysporum f. sp. Albedinis: A Comparative Review",
        authors: "Y Kaddouri, R Benabbes, S Ouahhoud, M Abdellattif, B Hammouti, ...",
        journal: "Molecules",
        volume: "27 (9), 2698",
        year: "2022",
        citations: 6,
        firstAuthor: true,
        field: "Antimicrobial",
    },
    {
        title: "Synthesis, experimental and theoretical studies of sesquiterpenic thiosemicarbazone and semicarbazone as organic corrosion inhibitors for stainless steel 321 in H2SO4 1M",
        authors: "A Bimoussa, Y Koumya, A Oubella, Y Kaddouri, M Fawzi, Y Laamari, ...",
        journal: "Journal of Molecular Structure",
        volume: "1253, 132276",
        year: "2022",
        citations: 16,
        firstAuthor: false,
        field: "Computational Chemistry",
    },
    {
        title: "Metal corrosion inhibition by triazoles: A review",
        authors: "I Merimi, A Bitari, Y Kaddouri, N Rezki, M Mohamed, R Touzani, ...",
        journal: "International journal of corrosion and scale inhibition",
        volume: "11 (2), 524-540",
        year: "2022",
        citations: 16,
        firstAuthor: false,
        field: "Corrosion",
    },
    {
        title: "Correlation between corrosion inhibition efficiency in sulfuric acid medium and the molecular structures of two newly eco-friendly pyrazole derivatives on iron oxide surface",
        authors: "N Mechbal, ME Belghiti, N Benzbiria, CH Lai, Y Kaddouri, Y Karzazi, ...",
        journal: "Journal of Molecular Liquids",
        volume: "331, 115656",
        year: "2021",
        citations: 54,
        firstAuthor: false,
        field: "Materials Chemistry",
    },
    {
        title: "Synthesis, characterization, reaction mechanism prediction and biological study of mono, bis and tetrakis pyrazole derivatives against Fusarium oxysporum f. sp. Albedinis with …",
        authors: "Y Kaddouri, F Abrigach, S Ouahhoud, R Benabbes, M El Kodadi, ...",
        journal: "Bioorganic Chemistry",
        volume: "110, 104696",
        year: "2021",
        citations: 26,
        firstAuthor: true,
        field: "Bioorganic Chemistry",
    },
    {
        title: "New heterocyclic compounds: synthesis, antioxidant activity and computational insights of nano-antioxidant as ascorbate peroxidase inhibitor by various cyclodextrins as drug …",
        authors: "Y Kaddouri, F Abrigach, EB Yousfi, B Hammouti, M El Kodadi, A Alsalme, ...",
        journal: "Current Drug Delivery",
        volume: "18 (3), 334-349",
        year: "2021",
        citations: 15,
        firstAuthor: true,
        field: "Heterocyclic Chemistry",
    },
    {
        title: "Synthetic Nitrogen Compounds as Efficient Corrosion Inhibitors for Metallic Materials in Aggressif Medium",
        authors: "Y KADDOURI, A TITI, I OUALDI, M EL KODADI, R TOUZANI, ...",
        journal: "Journal of Applied Science and Environmental Studies",
        volume: "4 (4)",
        year: "2021",
        citations: 1,
        firstAuthor: true,
        field: "Corrosion",
    },
    {
        title: "Rosemary essential oils: Extraction, GC/MS analysis, antioxidant activity with dft and in silico insights of prospective nano-antioxidants",
        authors: "I Oualdi, K Diass, S Azizi, M Dalli, Y Kaddouri, K Arhmir, R Touzani, ...",
        journal: "Journal of Applied Science and Environmental Studies",
        volume: "4 (4)",
        year: "2021",
        citations: 2,
        firstAuthor: false,
        field: "Analytical Chemistry",
    },
    {
        title: "Synthesis, Molecular Docking, MEP and SAR Analysis, ADME‐Tox Predictions, and Antimicrobial Evaluation of Novel Mono‐and Tetra‐Alkylated Pyrazole and Triazole Ligands",
        authors: "Y Kaddouri, B Bouchal, F Abrigach, M El Kodadi, M Bellaoui, R Touzani",
        journal: "Journal of Chemistry",
        volume: "2021 (1), 6663245",
        year: "2021",
        citations: 13,
        firstAuthor: true,
        field: "Computational Chemistry",
    },
    {
        title: "Mono-Alkylated Ligands Based on Pyrazole and Triazole Derivatives Tested Against Fusarium oxysporum f. sp. albedinis: Synthesis, Characterization, DFT, and …",
        authors: "Y Kaddouri, F Abrigach, S Ouahhoud, R Benabbes, M El Kodadi, ...",
        journal: "Frontiers in Chemistry",
        volume: "8, 559262",
        year: "2020",
        citations: 17,
        firstAuthor: true,
        field: "Heterocyclic Chemistry",
    },
    {
        title: "The inhibition behavior of two pyrimidine-pyrazole derivatives against corrosion in hydrochloric solution: Experimental, surface analysis and in silico approach studies",
        authors: "N Arrousse, R Salim, Y Kaddouri, D Zahri, F El Hajjaji, R Touzani, M Taleb, ...",
        journal: "Arabian Journal of Chemistry",
        volume: "13 (7), 5949-5965",
        year: "2020",
        citations: 141,
        firstAuthor: false,
        field: "Computational Chemistry",
    },
    {
        title: "Catecholase catalytic properties of copper (II) complexes prepared in-situ with heterocyclic ligands: Experimental and DFT study",
        authors: "Y Kaddouri, H Haddari, A Titi, EB Yousfi, A Chetouani, M El Kodadi, ...",
        journal: "Moroccan Journal of Chemistry",
        volume: "8 (1), 184-197",
        year: "2020",
        citations: 27,
        firstAuthor: true,
        field: "Coordination Chemistry",
    },
    {
        title: "Synthesis of two new pyrazole based ligands for the liquid–solid extraction of heavy metals Pb, Cd and Cu in the aqueous medium",
        authors: "A Boulouiz, I Hajji, Y Kaddouri, K Zaidi, R Touzani, B Hammouti",
        journal: "Materials Today: Proceedings",
        volume: "31, S190-S196",
        year: "2020",
        citations: 2,
        firstAuthor: false,
        field: "Materials Chemistry",
    },
    {
        title: "New thiazole, pyridine and pyrazole derivatives as antioxidant candidates: synthesis, DFT calculations and molecular docking study",
        authors: "Y Kaddouri, F Abrigach, EB Yousfi, M El Kodadi, R Touzani",
        journal: "Heliyon",
        volume: "6 (1)",
        year: "2020",
        citations: 112,
        firstAuthor: true,
        field: "Computational Chemistry",
    },
    {
        title: "Study of the catecholase catalytic properties of copper (II) complexes prepared in-situ with monodentate ligands",
        authors: "A Titi, M Al-Noaimi, Y Kaddouri, R El Ati, EB Yousfi, M El Kodadi, ...",
        journal: "Materials Today: Proceedings",
        volume: "13, 1134-1142",
        year: "2019",
        citations: 14,
        firstAuthor: false,
        field: "Coordination Chemistry",
    },
    {
        title: "Pyrazole Compounds: Synthesis, molecular structure, chemical reactivity, experimental and theoretical DFT FTIR spectra",
        authors: "Y Kaddouri, F Abrigach, N Mechbal, Y Karzazi, M El Kodadi, A Aouniti, ...",
        journal: "Materials Today: Proceedings",
        volume: "13, 956-963",
        year: "2019",
        citations: 18,
        firstAuthor: true,
        field: "Heterocyclic Chemistry",
    },
    {
        title: "Crystal structure of fac-bis [bis (pyridin-2-yl) methanamine] iron (II) 1, 1, 3, 3-tetracyano-2-(dicyanomethylidene) propane-1, 3-diide,[Fe (dipa) 2](tcpd)",
        authors: "Z Setifi, PWR Corfield, F Setifi, B Morgenstern, K Hegetschweiler, Y Kaddouri, ...",
        journal: "Structure Reports",
        volume: "74 (9), 1227-1230",
        year: "2018",
        citations: 1,
        firstAuthor: false,
        field: "Crystallography",
    },
    {
        title: "Synthesis of four new tridentate pyrazolic ligands",
        authors: "Y Kaddouri",
        journal: "Moroccan Journal of Heterocyclic Chemistry",
        volume: "16 (1)",
        year: "2017",
        citations: 5,
        firstAuthor: true,
        field: "Heterocyclic Chemistry",
    },
    {
        title: "Two tripodal pyrazolic ligands: application against corrosion of mild steel in HCl 1M",
        authors: "Y Kaddouri, A Takfaoui, M Lamsayah, M El Azzouzi, R Boyaala, ...",
        journal: "Moroccan Journal of Chemistry",
        volume: "5 (3), 467-475",
        year: "2017",
        citations: 4,
        firstAuthor: true,
        field: "Corrosion",
    },
    {
        title: "Tridentate pyrazole ligands: synthesis, characterization and corrosion inhibition properties with theoretical investigations",
        authors: "Y Kaddouri, A Takfaoui, F Abrigach, M El Azzouzi, A Zarrouk, F El-Hajjaji, ...",
        journal: "J. Mater. Environ. Sci",
        volume: "8 (3), 845-856",
        year: "2017",
        citations: 19,
        firstAuthor: true,
        field: "Corrosion",
    },
];

