// Animation and timing constants
export const ANIMATION_DELAYS = {
  SECTION_ENTER: 0.1,
  TITLE_ENTER: 0.1,
  SUBTITLE_ENTER: 0.2,
  BULLETS_ENTER: 0.3,
  BULLET_STAGGER: 0.1,
  STAR_ICON: 0.5,
} as const;

export const SCROLL_TIMEOUTS = {
  PROGRAMMATIC_SCROLL_RESET: 1000,
  COMPLETION_TOAST_AUTO_HIDE: 8000,
} as const;

export const VIEWPORT_THRESHOLDS = {
  SECTION_AMOUNT: 0.3,
  DETECTION_AMOUNT: 0.3,
} as const;

